run_name: WikiDiverse`
seed: 43
pretrained_model: '/home/jianbo/Code/MIMIC-master/Clip/clip-vit-base-patch32-main'
lr: 1e-4


data:
  num_entity: 132460
  kb_img_folder: /mnt/d/dataset/MIMIC/data/WikiDiverse/kb_image
  mention_img_folder: /mnt/d/dataset/MIMIC/data/WikiDiverse/mention_image
  qid2id: /mnt/d/dataset/MIMIC/data/WikiDiverse/qid2id.json
  entity: /mnt/d/dataset/MIMIC/data/WikiDiverse/kb_entity.json
  train_file: /mnt/d/dataset/MIMIC/data/WikiDiverse/wiki_diverse_train.json
  dev_file: /mnt/d/dataset/MIMIC/data/WikiDiverse/wiki_diverse_dev.json
  test_file: /mnt/d/dataset/MIMIC/data/WikiDiverse/wiki_diverse_test.json
  validation_results : /home/jianbo/Code/MIMIC-maxprob/codes/results/WikiDiverse/version_1/validation_results.pkl
  test_results: /home/jianbo/Code/MIMIC-maxprob/codes/results/WikiDiverse/version_1/test_results.pkl
  batch_size: 128
  num_workers: 8
  text_max_length: 40

  eval_chunk_size: 6000
  eval_batch_size: 20
  embed_update_batch_size: 512


model:
  input_hidden_dim: 512
  input_image_hidden_dim: 768
  hidden_dim: 96
  dv: 96
  dt: 512
  TGLU_hidden_dim: 96
  IDLU_hidden_dim: 96
  CMFU_hidden_dim: 96

selector:
  hidden_1_dim: 1024
  hidden_2_dim: 1024
  dropout: 0.5
  output_size: 2

trainer:
  accelerator: 'gpu'
  devices: 1
  max_epochs: 20
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 2
  log_every_n_steps: 30

selectorTrainer:
  accelerator: 'gpu'
  devices: 1
  max_epochs: 10
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 10
#  val_check_interval: 100
